# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0002_auto_20180213_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classified',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classified',
            name='seller_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
