# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0004_auto_20180213_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='aircraft_location',
            field=models.CharField(default='Vilnius, Lithuania', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classified',
            name='phone_number',
            field=models.CharField(default='+37063626733', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classified',
            name='seller_email',
            field=models.EmailField(default='mareliux@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
