# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-13 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0005_auto_20180213_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='classified',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
