# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0007_auto_20180213_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='classified_images')),
                ('classified', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classifieds.Classified')),
            ],
        ),
    ]
