# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 13:39
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0008_classifiedimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classified',
            options={'ordering': ['-date_time']},
        ),
        migrations.AlterField(
            model_name='classifiedimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='classified_images'),
        ),
    ]
