# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-15 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0009_auto_20180215_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='aircraft_make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.AircraftMake'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classified',
            name='aircraft_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.AircraftType'),
            preserve_default=False,
        ),
    ]
