# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0011_classified_commercial_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='classified_status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Inactive'), (3, 'Awaiting Payment')], default=1),
        ),
    ]
