# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0012_classified_classified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='payment_completed',
            field=models.BooleanField(default=True),
        ),
    ]
