# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0013_classified_payment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='commercial_aircraft',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
