# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0015_auto_20180219_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircrafttype',
            name='type_make',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classifieds.AircraftMake'),
            preserve_default=False,
        ),
    ]
