# Generated by Django 3.1.7 on 2021-03-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0019_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='price_usd',
            field=models.FloatField(),
        ),
    ]
