# Generated by Django 3.1.7 on 2021-04-02 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classifieds', '0020_auto_20210328_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classified',
            name='aircraft_location',
            field=models.CharField(max_length=255, validators=[django.core.validators.MaxLengthValidator(230, message='Address is too large')]),
        ),
        migrations.AlterField(
            model_name='classified',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(200, message='Name is too large')]),
        ),
        migrations.AlterField(
            model_name='classified',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(17, message='Not a valid entry'), django.core.validators.MinLengthValidator(8, message='Not a valid entry')]),
        ),
        migrations.AlterField(
            model_name='classified',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(200, message='The serial number is too large.')]),
        ),
        migrations.AlterField(
            model_name='classifiedimage',
            name='classified',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiple_imgs', to='classifieds.classified'),
        ),
    ]
